import 'package:flutter/material.dart';

/// Static icon key → IconData map used by category and subcategory tiles.
const Map<String, IconData> habitCategoryIconMap = {
  'account_balance_wallet': Icons.account_balance_wallet,
  'add_circle': Icons.add_circle,
  'auto_awesome': Icons.auto_awesome,
  'bedtime': Icons.bedtime,
  'block': Icons.block,
  'calendar_today': Icons.calendar_today,
  'camera_alt': Icons.camera_alt,
  'campaign': Icons.campaign,
  'checklist': Icons.checklist,
  'child_care': Icons.child_care,
  'cleaning_services': Icons.cleaning_services,
  'design_services': Icons.design_services,
  'directions_run': Icons.directions_run,
  'directions_walk': Icons.directions_walk,
  'eco': Icons.eco,
  'edit_note': Icons.edit_note,
  'explore': Icons.explore,
  'family_restroom': Icons.family_restroom,
  'favorite': Icons.favorite,
  'fitness_center': Icons.fitness_center,
  'folder': Icons.folder,
  'groups': Icons.groups,
  'handshake': Icons.handshake,
  'history': Icons.history,
  'house': Icons.house,
  'local_hospital': Icons.local_hospital,
  'medication': Icons.medication,
  'menu_book': Icons.menu_book,
  'music_note': Icons.music_note,
  'no_drinks': Icons.no_drinks,
  'no_food': Icons.no_food,
  'palette': Icons.palette,
  'park': Icons.park,
  'people': Icons.people,
  'phone_disabled': Icons.phone_disabled,
  'podcasts': Icons.podcasts,
  'psychology': Icons.psychology,
  'restaurant': Icons.restaurant,
  'savings': Icons.savings,
  'school': Icons.school,
  'self_improvement': Icons.self_improvement,
  'sentiment_satisfied': Icons.sentiment_satisfied,
  'shield': Icons.shield,
  'smoke_free': Icons.smoke_free,
  'spa': Icons.spa,
  'speaker_notes_off': Icons.speaker_notes_off,
  'sports': Icons.sports,
  'sports_esports': Icons.sports_esports,
  'sports_martial_arts': Icons.sports_martial_arts,
  'translate': Icons.translate,
  'trending_down': Icons.trending_down,
  'trending_up': Icons.trending_up,
  'videocam': Icons.videocam,
  'volunteer_activism': Icons.volunteer_activism,
  'water_drop': Icons.water_drop,
  'work_off': Icons.work_off,
};

IconData iconForKey(String? key) =>
    habitCategoryIconMap[key] ?? Icons.category_outlined;
